MODEL:
  BACKBONE:
    FREEZE_CONV_BODY_AT: -1
  DYHEAD:
    NUM_CLASSES: 81

SOLVER:
  STEPS: (0.67, 0.89)
  BASE_LR: 0.00001
  LANG_LR: 0.00001
  GATE_LR: 0.0001
  QUERY_LR: 0.00001
  # WEIGHT_DECAY: 0.05
  WEIGHT_DECAY: 0.0001
  WARMUP_ITERS: 2000
  # USE_AUTOSTEP: True

  TEST_WITH_INFERENCE: True

  CHECKPOINT_PERIOD: 99999999
  CHECKPOINT_PER_EPOCH: -1.0

TEST:
  DURING_TRAINING: False
  EVAL_TASK: detection

DATASETS:
  TRAIN: ("coco_grounding_train_for_obj365", )
  TEST: ("coco_2017_val", )
  USE_OVERRIDE_CATEGORY: True
  DISABLE_SHUFFLE: True
  FEW_SHOT: 5

VISION_QUERY:
  QUERY_BANK_PATH: MODEL/coco_query_5_sel.pth
  VISION_SCALE: 1.0
  PURE_TEXT_RATE: 0.
  TEXT_DROPOUT: 0.
  NUM_QUERY_PER_CLASS: 5
  MAX_QUERY_NUMBER: 5
  RANDOM_KSHOT: False



